### ISSUE TITLE
[PE-D][Tester C] Remove command bug when there are 2 events with the same name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W13-3/tp#187]
![image.png](https://raw.githubusercontent.com/KHsienKit/ped/main/files/fc42b699-e68d-4493-9b05-520db370469a.png)

When there are 2 events with the same name, the event that is higher up on the list gets removed. I cannot choose which event to remove

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: KHsienKit/ped#2

**Comment by jemehgoh** [comment]
Similar to #186 - issue is due to edit command not having duplicate entry checks
