### ISSUE TITLE
[PE-D][Tester C] Copy feature overwrites participant list of the other event

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-3/tp#191]
![image.png](https://raw.githubusercontent.com/KHsienKit/ped/main/files/ad68f69d-4517-431c-9fb6-424e138414ca.png)

If B_EVENT has a set of participants and the copy function was used to copy the participants from A_EVENT to B_EVENT, participants of B_EVENT is deleted and replaced by participants of A_EVENT.

I honestly expected participants of A_EVENT will be displayed on top of B_EVENT or vice versa

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: KHsienKit/ped#3

**Comment by jemehgoh** [comment]
This is the expected functionality for the command, will update the UG to clarify.

**Comment by jemehgoh** [comment]
The UG has been updated with the clarification.
