### ISSUE TITLE
[PE-D][Tester B] Sequence Diagram Error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-3/tp#230]
The lifeline exceeds the X , in page 30 of the developer guide. 

![image.png](https://raw.githubusercontent.com/Holy-An/ped/main/files/3fba97d6-7449-4778-b2ab-1cf3556aa99b.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Holy-An/ped#13

**Comment by jemehgoh** [comment]
Duplicate of #223.
