### ISSUE TITLE
Event search in "view" command is case-sensitive

### ISSUE THREAD

**Issue by jemehgoh** [AY2425S1-CS2113-W13-3/tp#236]
![image](https://github.com/user-attachments/assets/4cdb45e5-7f04-4fa9-b9f9-a9d827c5f3b1)

As shown above, when an event with the name "Origami workshop" is present in the list, but an event named "origami workshop" is searched for (which has a similar name, but different case), the program shows an error message. I would expect the search to match.

**Comment by jemehgoh** [comment]
Might just leave this as a thing in the UG (as making the search case-insensitive might limit functionality even more)

**Comment by LTK-1606** [comment]
I think should not make it case insensitive cos they r meant to be unique. But i think we gna add id right then should view using id instead of name

**Comment by jemehgoh** [comment]
If that's the case, then I will just leave this as is, and mention it in the User Guide (about case-sensitivity)
