### ISSUE TITLE
The status keyword for the "mark" commands is case-sensitive

### ISSUE THREAD

**Issue by jemehgoh** [AY2425S1-CS2113-W13-3/tp#238]
![image](https://github.com/user-attachments/assets/08ce7e10-2629-4279-8d9b-7ebc9ae3a8d3)

As shown above, when an event is marked with the status keyword `DONE`, the program shows an invalid command message. I would expect this keyword to be accepted as valid (since `done` is one of the valid status keywords, as mentioned in the  _User Guide_)

**Comment by LTK-1606** [comment]
ur input does not have the '-s' flag

**Comment by jemehgoh** [comment]
Ok my bad
